spring:
  application:
    name: ticketDealer
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  rooms:
    - number: 1
      rows: 10
      seatsPerRow: 20
    - number: 2
      rows: 8
      seatsPerRow: 15
    - number: 3
      rows: 2
      seatsPerRow: 3
    - number: 10
      rows: 10
      seatsPerRow: 10